import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from lanes import build

lanes = [
 {"name": "ONLINE SERVING PATH  ·  GET /recommendations (fast)", "color": "#1a73e8",
  "nodes": [("Shopper", "user", "actor", "user (pseudonymised) or\nsession id + context id"),
            ("API gateway", "lb", "network", "auth · LB · throttling"),
            ("Recommendation\nservice", "run", "compute", "orchestrator (Lambdas):\nno business logic"),
            ("Redis cache", "bolt", "ops", "recs per user · refreshed\non hit AND miss"),
            ("Online feature\nstore", "db", "data", "latest viewed / purchased\nvector, keyed by user id"),
            ("Embedding store\n(nearest neighbours)", "sparkle", "ai", "256-d × 4 B × 100M items\n≈ 100 GB, off-box"),
            ("Ranker + filters", "chart", "compute", "business objective;\ndrop out-of-stock & purchased")],
  "edges": [(0, "request", "Request carries user key, context (current item/page) and pagination"),
            (1, "", "Gateway routes to the serverless orchestrator"),
            (2, "lookup", "Cache hit returns precomputed recommendations immediately"),
            (3, "miss", "On a miss, fetch the user's online feature vector (recent behaviour, <5 min fresh)"),
            (4, "similar items", "Dot-product / nearest-neighbour search finds items similar to what the user viewed or bought"),
            (5, "candidates", "Ranker orders candidates, applies deterministic filters; result goes back to the user and into the cache")]},
 {"name": "NEAR-REAL-TIME PIPELINE  ·  keeps the online feature store fresh", "color": "#00897b",
  "nodes": [("Clickstream /\norder events", "globe", "network", "views · carts · purchases ·\nreturns"),
            ("Event collector", "bolt", "compute", ""),
            ("Kafka", "bolt", "compute", "open source, avoids lock-in\n(alt: Kinesis)"),
            ("Flink stream\nprocessing", "pipeline", "compute", "enrich via metadata cache,\ntransform to feature vector"),
            ("Online feature\nstore", "db", "data", "updated continuously")],
  "edges": [(0, "emit", "Upstream services (storefront, payments, orders) log what customers do"),
            (1, "publish", "High-volume event stream (~30k events/s average)"),
            (2, "consume", "Stream processor enriches events (e.g. product title/category from a fast cache)"),
            (3, "write", "Writes the latest per-user feature vector used on the serving path")]},
 {"name": "OFFLINE TRAINING PIPELINE  ·  hourly/daily batch", "color": "#F29900",
  "nodes": [("Kafka", "bolt", "compute", "duplicate of the stream"),
            ("Spark batch jobs", "pipeline", "compute", "hourly or daily snapshots"),
            ("Offline feature\nstore", "db", "data", "event sequences that led\nto purchases"),
            ("Model training /\nvalidation", "sparkle", "ai", "precision · accuracy · AUC\nvs history"),
            ("New embedding\nsnapshot", "registry", "dev", "published to the embedding\nstore after A/B check")],
  "edges": [(0, "batch", "Same stream is also batched into snapshots for offline processing"),
            (1, "join", "Jobs combine snapshots with historical sequences"),
            (2, "train", "Model learns which sequences end in purchases"),
            (3, "publish", "Only if offline metrics pass; then A/B test old vs new model on a traffic split, monitoring click-through and purchase attribution")]},
]
build(os.path.join(os.path.dirname(__file__), "architecture.svg"), "Design a product recommendation system",
      "Evolved from a simple design: cache → feature store → embeddings → ranker; Kafka/Flink online + Spark offline", lanes,
      notes=["Scale: 50M DAU, 100M products, 20 page views/user/day → ~11k req/s average, ~35k peak; ~50 events/user/day → ~29k events/s (the video said ~100k)",
             "Freshness requirement: recommendations reflect behaviour within 5 minutes; filters: out-of-stock and already-purchased",
             "Unhappy path: cold start / no user id → fall back to contextual signals (current category, device, geo, trending)"])
