import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from lanes import build

lanes = [
 {"name": "UPLOAD PATH  ·  asynchronous (writes: ~250 photos/s)", "color": "#1a73e8",
  "nodes": [("Mobile / web\nclient", "user", "actor", "POST /v1/photos"),
            ("API gateway", "lb", "network", "auth · rate limit"),
            ("Geo-aware LB", "globe", "network", "nearest region"),
            ("Media service", "run", "compute", "validates size limits"),
            ("Message queue", "bolt", "compute", "decouples slow upload"),
            ("Loader", "run", "compute", "ID generator for photo ids"),
            ("Object storage +\nSQL metadata", "bucket", "data", "S3 bytes · sharded SQL\nrows (by user id)")],
  "edges": [(0, "upload", "Client uploads a photo through the gateway (rate limiting, authN/Z for 1B users)"),
            (1, "", "Geo-aware load balancer picks the nearest servers for the user's region"),
            (2, "", "Media service validates the request (size limits)"),
            (3, "enqueue", "Request is queued so the user does not wait on the heavy write"),
            (4, "dequeue", "Loader takes the job and assigns a unique photo id"),
            (5, "persist", "Bytes to object storage; photo metadata (owner, title, location, url) to the relational store")]},
 {"name": "VIEW PHOTO  ·  read path", "color": "#00897b",
  "nodes": [("Client", "user", "actor", "GET /v1/photos/{id}"),
            ("Media service", "run", "compute", "via gateway + LB"),
            ("Retriever", "run", "compute", "photo id → metadata"),
            ("SQL metadata", "db", "data", "storage location"),
            ("CDN", "globe", "network", "edge cache"),
            ("Object storage", "bucket", "data", "origin on miss")],
  "edges": [(0, "get photo", "Client requests a photo by id"),
            (1, "", "Media service delegates to the retriever"),
            (2, "lookup", "Retriever reads the photo's metadata to find where the object lives"),
            (3, "url", "Metadata returns the storage location"),
            (4, "fetch", "Served from the nearest CDN edge if cached, otherwise pulled from object storage and cached")]},
 {"name": "NEWS FEED  ·  precomputed, < 1 s", "color": "#F29900",
  "nodes": [("Client login", "user", "actor", "GET /v1/feed"),
            ("Feed service", "run", "compute", "reads cache first"),
            ("Feed cache", "bolt", "ops", "per-user feed, TTL"),
            ("Feed generator", "chart", "compute", "scheduled every 15-20 min\n+ forced on miss"),
            ("Metadata +\nfeed store", "db", "data", "followers · activity · NoSQL\nfeed rows (user id, sequence)"),
            ("Celebrity\nhandling", "policy", "security", "no push to 100M followers;\nmerge latest post at read time")],
  "edges": [(0, "login", "Typical entry: user opens the app and expects the latest posts from followees"),
            (1, "check cache", "Feed service checks for a fresh feed (with an expiry threshold)"),
            (2, "miss / stale", "On a miss or stale feed, a forced generation builds at least the top 10-20 posts"),
            (3, "followers + activity", "Generator uses followees, last-login time and other activity signals; dormant users are deprioritised"),
            (4, "hot users", "For users with huge follower counts, the feed is composed at read time from their latest posts instead of pre-pushed")]},
]
build(os.path.join(os.path.dirname(__file__), "architecture.svg"), "Design Instagram",
      "Upload / view / follow / news feed · read-heavy · object storage + sharded SQL + NoSQL feed · CDN + pre-populated feeds", lanes,
      notes=["Scale: 1B users, 25% DAU = 250M; 10 feed loads/day each → 2.5B reads/day ≈ 25k reads/s × 200 KB ≈ 5 GB/s",
             "Writes: 10% of DAU upload one photo = 25M/day ≈ 250/s ≈ 50 MB/s; storage ≈ 5 TB/day ≈ 1.8 PB/year (the video's '60-100 TB/yr' figure is an arithmetic slip)",
             "NFRs: high availability, geographically distributed users, feed < 1 s, near-zero data loss. Subscribe API writes follower rows to SQL"])
