import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from lanes import build

lanes = [
 {"name": "UPLOAD + TRANSCODE", "color": "#1a73e8",
  "nodes": [("Creator", "user", "actor", "POST upload\n(user id, video id, title, tags)"),
            ("API gateway +\nLB", "lb", "network", "authN/Z · health checks"),
            ("Upload service", "run", "compute", "captures size · user · device"),
            ("Raw blob store", "bucket", "data", "S3-style · parallel/chunked\nupload · durable"),
            ("Queue → Transcoder", "pipeline", "compute", "multi-step jobs,\nworker nodes"),
            ("Transcoded blob store", "bucket", "data", "chunks × formats ×\nresolutions"),
            ("Metadata SQL", "db", "data", "video · user tables")],
  "edges": [(0, "upload", "Creator uploads a video with metadata (title, tags, location)"),
            (1, "", "Gateway authenticates/authorises; load balancer distributes and health-checks"),
            (2, "raw video", "Upload service records details and stores the raw file straight in blob storage first, so reliability is guaranteed"),
            (3, "enqueue", "A queue absorbs bursts of uploads so users are not blocked"),
            (4, "transcode", "Transcoder workers (one queue per step) produce chunks and device/resolution variants, also compressing to save storage"),
            (5, "metadata", "Metadata (title, owner, location, tags) goes into a SQL table; schema is fixed, so SQL is fine")]},
 {"name": "WATCH  ·  adaptive streaming + CDN", "color": "#00897b",
  "nodes": [("Viewer", "user", "actor", "watch(user, video, offset,\nresolution)"),
            ("API gateway +\nLB", "lb", "network", ""),
            ("Watch service", "run", "compute", "picks format from\ndevice + bandwidth"),
            ("Video controller", "policy", "compute", "popular? nearest CDN?\n(key-value by location)"),
            ("CDN (multi-region)", "globe", "network", "leader + replicas"),
            ("Transcoded blob store", "bucket", "data", "origin on miss;\nCDN is back-filled")],
  "edges": [(0, "watch", "Request carries user id, video id, offset (resume point) and resolution"),
            (1, "", "Same gateway and load balancer as upload"),
            (2, "metadata", "Watch service reads device/screen info and chooses the rendition"),
            (3, "route", "Controller checks whether the video is popular and finds the nearest CDN by user location"),
            (4, "miss", "On a CDN miss, fetch from the transcoded store and populate the CDN for next time. Adaptive bit-rate (MPEG-DASH style) switches resolution as bandwidth changes")]},
 {"name": "SEARCH", "color": "#F29900",
  "nodes": [("Upload metadata", "db", "data", "title · channel ·\ndescription · tags"),
            ("Extraction", "filter", "compute", "keywords → JSON doc"),
            ("Keyword index", "bolt", "ops", "key-value (Redis /\nDynamoDB): keyword → video ids"),
            ("Search service", "run", "compute", "fuzzy match for typos;\nrank by search frequency"),
            ("Queue (lazy load)", "pipeline", "compute", "first 10 results,\nrest streamed in"),
            ("Searcher", "user", "actor", "scrolls results")],
  "edges": [(0, "on upload", "In parallel with transcoding, metadata is mined for searchable terms"),
            (1, "keywords", "Extracted keywords are written to a key-value store: keyword → list of video ids"),
            (2, "query", "A search looks up the keyword (fuzzy search handles misspellings, like 'did you mean'); entries ranked by search frequency"),
            (3, "results", "Results are fetched lazily: show the first 10 now, push the rest via a queue as the user scrolls"),
            (4, "page", "Video ids resolve to metadata and playable URLs")]},
]
build(os.path.join(os.path.dirname(__file__), "architecture.svg"), "Design YouTube",
      "Upload → transcode → CDN streaming · adaptive bitrate · keyword-index search · replication everywhere", lanes,
      notes=["Scale: 2B users, 500M DAU × 5 videos = 2.5B views/day; 100M creators × 2 uploads = 200M videos/day × 100 MB = 20 PB/day",
             "Read-heavy; requirements: high availability, scalability, reliability (uploaded video is never lost), low latency / no buffering",
             "Left out: likes, comments, dislikes. Replicas and multiple CDNs for scale; a leader CDN as source of truth"])
