import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from lanes import build

lanes = [
 {"name": "P2P TRANSFER  ·  saga + transactional outbox across shards", "color": "#1a73e8",
  "nodes": [("Mobile app", "user", "actor", "POST /v1/transfers\n+ Idempotency-Key"),
            ("API gateway", "lb", "network", "auth · TLS"),
            ("Transfer service", "run", "compute", "Redis idempotency check →\nsync fraud check"),
            ("Ledger Postgres\n(sender shard)", "db", "data", "ACID tx: lock sender row,\ndebit, double-entry rows,\ninsert outbox event"),
            ("Debezium CDC → Kafka", "bolt", "compute", "tails the write-ahead log,\npublishes saga events"),
            ("Credit worker\n(receiver shard)", "run", "compute", "local tx credits receiver; ack Kafka\nonly after commit")],
  "edges": [(0, "send money", "Client generates a unique idempotency key per payment attempt"),
            (1, "", "Gateway validates the token and routes"),
            (2, "debit", "Duplicate retries are blocked in O(1) via Redis; fraud service scores velocity and IP in milliseconds"),
            (3, "outbox event", "Business change and the outgoing event commit atomically, so nothing is lost between DB and Kafka"),
            (4, "credit event", "Receiver may live on another shard, so no cross-shard transaction is used")]},
 {"name": "AFTER THE CREDIT  ·  fan-out and rollback", "color": "#00897b",
  "nodes": [("Kafka", "bolt", "compute", "success / failure events"),
            ("Notification svc", "run", "compute", "APNs / FCM push"),
            ("Feed service", "run", "compute", "append-only history"),
            ("Cassandra", "db", "data", "social/transaction feed,\ncursor pagination"),
            ("Refund worker", "shield", "security", "on credit failure (e.g. frozen\naccount) re-credits sender")],
  "edges": [(0, "consume", "Downstream systems are decoupled from the ledger"),
            (1, "consume", "Same event also drives the feed"),
            (2, "write", "Historical log lives outside the relational ledger"),
            (3, "compensate", "Failure event triggers a compensating transaction on the first shard (self-healing eventual consistency)")]},
 {"name": "FUNDING FROM A BANK  ·  async settlement + reconciliation", "color": "#F29900",
  "nodes": [("Client", "user", "actor", "POST /v1/funding/deposit"),
            ("Funding service", "run", "compute", "state machine: created →\nprocessing; balance NOT yet raised"),
            ("Bank adapter", "pipeline", "compute", "ISO 8583 / Stripe API"),
            ("External bank", "globe", "network", "may take days"),
            ("Webhook listener", "lb", "network", "verify cryptographic signature"),
            ("Reconciliation\nworkers", "chart", "ops", "settle + write double-entry rows;\nnightly sweeper polls bank for stuck rows")],
  "edges": [(0, "request", "Pull from a linked bank account"),
            (1, "translate", "Row written as pending in the ledger DB"),
            (2, "submit", "Adapter formats the legacy request"),
            (3, "HTTP POST", "Bank calls back when funds clear"),
            (4, "via Kafka", "Validated payloads are buffered so nothing is lost if the DB is busy")]},
]
build(os.path.join(os.path.dirname(__file__), "architecture.svg"), "Design a digital wallet (Cash App)",
      "Idempotency · double-entry ledger · deadlock-free locking · saga + transactional outbox · reconciliation", lanes,
      notes=["Scale/NFRs: 100M+ users, 10k+ TPS peak, < 200 ms for wallet-to-wallet, 99.99% availability, strict consistency for money, idempotent retries",
             "Never just UPDATE balance: keep an immutable double-entry ledger (debit and credit rows that sum to zero); balance = sum of entries, wallet balance is a reconciled cache",
             "Avoid deadlocks by locking rows in sorted id order. Hot wallets: batch incoming credits through Kafka and apply one aggregated credit"])
